### PR TITLE
Add and Fix Tutorials Weeks 0-3

### PR DESCRIPTION
**Pull request by slushiegoose**
This PR:

- Adds the slides and recordings to **Week 0 - Introduction to AI**
- Adds the exercises and slides to **Week 1 - Introduction to Python**
- Fixes the Notebook URL  for **Week 2 - Regression** (uclais/ml-tutorials-season-4#3)
- Adds the description to **Week 3 - Classification**

## Week 0
Week 0

## Week 1
Week 1

## Week 2
Week 2

## Week 3
Week 3

### CODE REVIEW

**Review by angela24680403 — APPROVED** [review]
lgtm!

**Comment by TheRootOf3** [comment]
It's not directly related to this PR, but it may be worth changing the week number here:
image

**Review by TheRootOf3 — APPROVED** [review]
LGTM

**Comment by TheRootOf3** [comment]
> It's not directly related to this PR, but it may be worth changing the week number here: image

I created an issue and a PR for that @angela24680403 @slushiegoose:
- Issue uclais/ml-tutorials-season-4#4
- PR uclais/ml-tutorials-season-4#5

**Pull request merged**
