### PR TITLE
Add Regression Recording & Classification Notebook and Slides

### PR DESCRIPTION
**Pull request by slushiegoose**
This PR adds the Regression (Week 2) Recording and also the Classification (Week 3) Notebook and Slides

## Week 2
image

## Week 3
image

### CODE REVIEW

**Comment by angela24680403** [comment]
Could you add description for demo nb that there are 3: one for logistic reg, svm/trees, kmeans? thanks!

**Review by TheRootOf3 — COMMENTED** [review]
LGTM

**Comment by TheRootOf3** [comment]
> Could you add description for demo nb that there are 3: one for logistic reg, svm/trees, kmeans? thanks!

@slushiegoose I'll approve, once this is resolved!

**Comment by slushiegoose** [comment]
image

**Review by angela24680403 — APPROVED** [review]
Looks awesome thanks suhail!

**Review by TheRootOf3 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
