### PR TITLE
Website updates for 2024-25 

### PR DESCRIPTION
**Pull request by levon-d**

### CODE REVIEW

**Review by Sergikavtaradze — DISMISSED** [review]
We shouldn;t change last years tutorials files, just store it in an archived tab, because Angela kindly asked me to do so.

**Comment by levon-d** [comment]
> We shouldn;t change last years tutorials files, just store it in an archived tab, because Angela kindly asked me to do so.

Thank you for this comment. I will make the necessary changes promptly.

**Comment by Sergikavtaradze** [comment]
The website structure looks good.

Maybe need to change the climate hack section markdown text to say, more details about this year's competition will be announced in term 2.

**Review by Sergikavtaradze — APPROVED** [review]
The website structure looks good.

Maybe need to change the climate hack section markdown text to say, more details about this year's competition will be announced in term 2, but for now it is okay.

**Pull request merged**
